[custom]
;不要随意改变关键字，否则会导致出错
;设置规则标志位
; AI
ruleset=AI,https://yfamilys.com/rule/ai.list
; 中国大陆域名直连
ruleset=DIRECT,[]GEOSITE,CN
; 中国大陆 IP 直连
ruleset=DIRECT,[]GEOIP,CN
ruleset=节点选择,[]FINAL

;设置分组标志位
custom_proxy_group=节点选择`select`[]DIRECT`.*
custom_proxy_group=AI`select`.*`[]DIRECT`
;设置分组标志位
enable_rule_generator=true
overwrite_original_rules=true
